---
- name: Configuração inicial de todas as VMs
  hosts: all
  become: yes
  roles:
    - common

- name: Configurar Docker hosts
  hosts: docker
  become: yes
  roles:
    - docker

- name: Configurar cluster K3s
  hosts: k3s
  become: yes
  roles:
    - k3s
    